import 'package:floor/floor.dart';
import 'package:healthcare_for_u/database/entities/user.dart';

//Here, we are saying to floor that this is a class that defines an entity
@Entity(
  tableName: 'Activity',
  foreignKeys: [
    ForeignKey(
      childColumns: ['userId'],
      parentColumns: ['id'],
      entity: User,
      onDelete: ForeignKeyAction.noAction,
      onUpdate: ForeignKeyAction.cascade,
    )
  ],
)
//@entity
class Activity {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

// username
  final int userId;

  // date
  final DateTime date;

// steps
  final int steps;

  // floors
  final double distance;

// calories
  final int calories;

// minutes
  final double minutes;

  //Default constructor
  Activity(this.id, this.userId, this.date, this.steps, this.calories,
      this.distance, this.minutes);
}//Activity