import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class Activity {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

// username
  final String user;

  // date
  final DateTime date;

// steps
  final int steps;

  // floors
  final int floors;

// calories
  final int calories;

// minutes
  final double minutes;

  //Default constructor
  Activity(this.id, this.user, this.date, this.steps, this.calories,
      this.floors, this.minutes);
}//Todo