import 'package:floor/floor.dart';

//Here, we are saying to floor that this is a class that defines an entity
@entity
class User {
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  @PrimaryKey(autoGenerate: true)
  final int? id;

  final String username;

  final String password;

  final bool isAuthorized;

  //Default constructor
  User(this.id, this.username, this.password, this.isAuthorized);
}//Todo